import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  es: {
    'company.name': 'DataSmart',
    'company.tagline': 'Transformando datos en decisiones inteligentes',
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'hero.category': 'ANÁLISIS DE DATOS Y AUTOMATIZACIÓN',
    'hero.title': 'Transformamos tus datos en decisiones inteligentes',
    'hero.subtitle': 'Ofrecemos soluciones personalizadas de análisis de datos y automatización adaptadas a tu negocio, ayudándote a optimizar procesos, reducir costos y mejorar la toma de decisiones.',
    'hero.cta': 'Conoce nuestros servicios',
    'hero.dashboard.title': 'Panel de Análisis',
    'hero.dashboard.live_data': 'Datos en Vivo',
    'hero.dashboard.data_processing': 'Procesamiento de Datos',
    'hero.dashboard.processing_active': 'Activo',
    'hero.dashboard.realtime_analytics': 'Análisis en Tiempo Real',
    'hero.dashboard.analytics_running': 'Ejecutándose',
    'hero.dashboard.data_accuracy': 'Precisión de Datos',
    'hero.dashboard.key_metrics': 'Métricas Clave',
    'hero.dashboard.response': 'Respuesta',
    'hero.dashboard.records': 'Registros',
    'hero.dashboard.uptime': 'Tiempo Activo',
    'hero.robot.greeting': '¡Hola! ¿Te ayudo con tus datos? 🤖💙',
    'market.category': 'OPORTUNIDAD DE MERCADO',
    'market.title': 'Un Mercado de $274 Mil Millones en Análisis de Datos',
    'market.subtitle': '90% de las empresas recolectan datos, pero solo el 23% los convierte en ventaja competitiva. La demanda global de análisis de datos crece 25% anualmente, pero la mayoría de organizaciones carece de capacidades internas.',
    'market.intro': 'Cada organización tiene necesidades únicas de datos. Identificamos 5 segmentos principales con oportunidades inmediatas de impacto.',
    'market.pymes.title': 'PYMEs (85% del mercado)',
    'market.pymes.desc': 'Solo 1 de cada 4 PYMEs utiliza análisis de datos avanzado. Pierden en promedio $164,000 anuales por decisiones basadas en intuición en lugar de datos.',
    'market.pymes.solution': 'ROI promedio 340% en 6 meses. Dashboards automatizados desde $2,500.',
    'market.startups.title': 'Startups (Crecimiento 45% anual)',
    'market.startups.desc': '73% de startups fallidas no analizaron correctamente su mercado objetivo. Los founders dedican 40% de su tiempo a reportes manuales.',
    'market.startups.solution': 'Reducción 80% tiempo en reportes. Analytics predictivo desde $1,800.',
    'market.growing.title': 'Empresas en Crecimiento',
    'market.growing.desc': 'Al duplicar su tamaño, generan 10x más datos. 68% experimenta "parálisis por datos" - demasiada información, pocas decisiones accionables.',
    'market.growing.solution': 'Aumento 150% velocidad de decisiones. Sistemas escalables desde $4,200.',
    'market.departments.title': 'Departamentos Corporativos',
    'market.departments.desc': 'Marketing, Ventas y Operaciones gastan $89,000 promedio en herramientas que no se integran. 54% de proyectos de BI corporativos fallan.',
    'market.departments.solution': 'Integración completa sistemas existentes. Proyectos desde $6,500.',
    'market.ngos.title': 'ONGs (Sector $1.5T global)',
    'market.ngos.desc': 'Pierden 30% de donaciones potenciales por no poder demostrar impacto cuantificable. Solo 15% utiliza analytics para optimizar programas.',
    'market.ngos.solution': 'Aumento 45% en captación fondos. Reportes impacto desde $1,200.',
    'market.acronyms': '*Datos de McKinsey, Gartner y Harvard Business Review 2024 | PYMEs: Pequeñas y Medianas Empresas',
    'services.title': 'Nuestros Servicios',
    'services.what_we_offer': 'Qué ofrecemos',
    'services.subtitle': 'Desarrollamos soluciones a medida que permiten aprovechar al máximo el valor de tus datos, desde la automatización de procesos hasta la visualización avanzada.',
    'services.automation.title': 'Automatización de Procesos',
    'services.visualization.title': 'Visualización de Datos',
    'services.extraction.title': 'Extracción y Procesamiento',
    'services.consulting.title': 'Consultoría en Análisis',
    'services.training.title': 'Formación y Capacitación',
    'services.unstructured.title': 'Análisis de Datos No Estructurados',
    'services.ai.title': 'Integración con IA',
    'services.analytics.title': 'Análisis de Datos',
    'services.analytics.desc': 'Transformamos datos complejos en insights accionables que impulsan la toma de decisiones estratégicas.',
    'services.automation.desc': 'Optimizamos tareas repetitivas y manuales para liberar tiempo valioso de tu equipo, reducir errores y mejorar la eficiencia operativa.',
    'services.visualization.desc': 'Transformamos datos complejos en visualizaciones interactivas y dashboards que facilitan la comprensión y toma de decisiones efectivas.',
    'services.extraction.desc': 'Extraemos, transformamos y limpiamos datos de múltiples fuentes para convertirlos en información valiosa y accionable para tu negocio.',
    'services.consulting.desc': 'Asesoramos y desarrollamos estrategias para implementar una cultura data-driven en tu organización, identificando KPIs clave y oportunidades de mejora.',
    'services.training.desc': 'Programas de formación personalizados para que tu equipo desarrolle habilidades analíticas y aproveche al máximo las herramientas disponibles.',
    'services.unstructured.desc': 'Extraemos insights valiosos de textos, imágenes y comunicaciones mediante técnicas avanzadas de procesamiento y análisis inteligente.',
    'services.ai.desc': 'Implementamos soluciones de inteligencia artificial personalizadas que automatizan procesos complejos y mejoran la capacidad predictiva de tu empresa.',
    'process.category': 'NUESTRA METODOLOGÍA',
    'process.title': 'Proceso de Trabajo',
    'process.subtitle': 'Seguimos un enfoque estructurado pero flexible que garantiza resultados óptimos en cada proyecto.',
    'process.step1.title': 'Diagnóstico',
    'process.step1.desc': 'Analizamos tu situación actual, identificamos oportunidades y definimos objetivos claros.',
    'process.step2.title': 'Diseño',
    'process.step2.desc': 'Desarrollamos una estrategia personalizada y planificamos la solución óptima para tus necesidades.',
    'process.step3.title': 'Implementación',
    'process.step3.desc': 'Ejecutamos la solución con un enfoque ágil, permitiendo ajustes durante el proceso.',
    'process.step4.title': 'Optimización',
    'process.step4.desc': 'Monitorizamos resultados, refinamos la solución y garantizamos la transferencia de conocimiento.',
    'process.diagram.title': 'Flujo de Trabajo',
    'process.diagram.subtitle': 'Un proceso iterativo y adaptativo para maximizar el valor de tus datos.',
    'about.title': 'Por qué elegir DataSmart',
    'about.experience': 'Experiencia Comprobada',
    'about.experience.desc': 'Años de experiencia ayudando a empresas de todos los tamaños a aprovechar el poder de sus datos.',
    'about.innovation': 'Innovación Constante',
    'about.innovation.desc': 'Utilizamos las últimas tecnologías y metodologías para entregar soluciones de vanguardia.',
    'about.results': 'Resultados Medibles',
    'about.results.desc': 'Nos enfocamos en generar impacto real y medible en los indicadores clave de nuestros clientes.',
    'contact.title': 'Comienza tu transformación digital',
    'contact.subtitle': 'Contáctanos para una consulta gratuita y descubre cómo podemos ayudar a tu empresa.',
    'contact.cta': 'Contactar ahora',
    'stats.projects': 'Proyectos Completados',
    'stats.clients': 'Clientes Satisfechos',
    'stats.efficiency': 'Mejora en Eficiencia',
    'stats.roi': 'ROI Promedio',
    'why_us.category': 'POR QUÉ ELEGIRNOS',
    'why_us.title': 'Nuestro Enfoque Diferenciado',
    'why_us.subtitle': 'Combinamos expertise técnico con un profundo entendimiento del negocio para ofrecer soluciones que generan impacto real y medible.',
    'why_us.scalable.title': 'Soluciones Escalables',
    'why_us.scalable.desc': 'Nuestras soluciones crecen con tu negocio, adaptándose a tus necesidades actuales y futuras sin necesidad de reinversiones constantes.',
    'why_us.integral.title': 'Enfoque Integral',
    'why_us.integral.desc': 'Combinamos datos, tecnología y estrategia de negocio para ofrecer soluciones completas que generan valor inmediato y sostenible.',
    'why_us.processing.title': 'Procesamiento Inteligente',
    'why_us.processing.desc': 'Especialistas en extraer valor de múltiples formatos (texto, imagen, audio, video) mediante tecnologías avanzadas de IA.',
    'why_us.development.title': 'Desarrollo a Medida',
    'why_us.development.desc': 'Creamos aplicaciones interactivas con tecnologías modernas como React/Next.js adaptadas específicamente a tus necesidades y flujos de trabajo.',
    'why_us.support.title': 'Acompañamiento Continuo',
    'why_us.support.desc': 'No solo implementamos soluciones, sino que te acompañamos en todo el proceso, asegurando adopción y maximizando el retorno de inversión.',
    'why_us.results.title': 'Resultados Medibles',
    'why_us.results.desc': 'Definimos KPIs claros para cada proyecto, garantizando resultados tangibles y un retorno de inversión cuantificable desde el inicio.'
  },
  en: {
    'company.name': 'DataSmart',
    'company.tagline': 'Transforming data into smart decisions',
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.category': 'DATA ANALYSIS AND AUTOMATION',
    'hero.title': 'We transform your data into smart decisions',
    'hero.subtitle': 'We offer personalized data analysis and automation solutions tailored to your business, helping you optimize processes, reduce costs and improve decision making.',
    'hero.cta': 'Learn about our services',
    'hero.dashboard.title': 'Analytics Dashboard',
    'hero.dashboard.live_data': 'Live Data',
    'hero.dashboard.data_processing': 'Data Processing',
    'hero.dashboard.processing_active': 'Active',
    'hero.dashboard.realtime_analytics': 'Real-time Analytics',
    'hero.dashboard.analytics_running': 'Running',
    'hero.dashboard.data_accuracy': 'Data Accuracy',
    'hero.dashboard.key_metrics': 'Key Metrics',
    'hero.dashboard.response': 'Response',
    'hero.dashboard.records': 'Records',
    'hero.dashboard.uptime': 'Uptime',
    'hero.robot.greeting': 'Hello! Can I help you with your data? 🤖💙',
    'market.category': 'MARKET OPPORTUNITY',
    'market.title': 'A $274 Billion Market in Data Analytics',
    'market.subtitle': '90% of companies collect data, but only 23% convert it into competitive advantage. Global demand for data analytics grows 25% annually, but most organizations lack internal capabilities.',
    'market.intro': 'Each organization has unique data needs. We identify 5 main segments with immediate impact opportunities.',
    'market.pymes.title': 'SMEs (85% of market)',
    'market.pymes.desc': 'Only 1 in 4 SMEs uses advanced data analytics. They lose an average of $164,000 annually from intuition-based decisions instead of data-driven ones.',
    'market.pymes.solution': 'Average ROI 340% in 6 months. Automated dashboards from $2,500.',
    'market.startups.title': 'Startups (45% annual growth)',
    'market.startups.desc': '73% of failed startups didn\'t properly analyze their target market. Founders spend 40% of their time on manual reporting.',
    'market.startups.solution': '80% reduction in reporting time. Predictive analytics from $1,800.',
    'market.growing.title': 'Growing Companies',
    'market.growing.desc': 'When doubling in size, they generate 10x more data. 68% experience "data paralysis" - too much information, few actionable decisions.',
    'market.growing.solution': '150% increase in decision speed. Scalable systems from $4,200.',
    'market.departments.title': 'Corporate Departments',
    'market.departments.desc': 'Marketing, Sales and Operations spend $89,000 average on tools that don\'t integrate. 54% of corporate BI projects fail.',
    'market.departments.solution': 'Complete integration of existing systems. Projects from $6,500.',
    'market.ngos.title': 'NGOs ($1.5T global sector)',
    'market.ngos.desc': 'Lose 30% of potential donations by not being able to demonstrate quantifiable impact. Only 15% use analytics to optimize programs.',
    'market.ngos.solution': '45% increase in fundraising. Impact reports from $1,200.',
    'market.acronyms': '*Data from McKinsey, Gartner and Harvard Business Review 2024 | SMEs: Small and Medium Enterprises',
    'services.title': 'Our Services',
    'services.what_we_offer': 'What we offer',
    'services.subtitle': 'We develop customized solutions that allow you to maximize the value of your data, from process automation to advanced visualization.',
    'services.automation.title': 'Process Automation',
    'services.visualization.title': 'Data Visualization',
    'services.extraction.title': 'Extraction and Processing',
    'services.consulting.title': 'Analytics Consulting',
    'services.training.title': 'Training and Capacity Building',
    'services.unstructured.title': 'Unstructured Data Analysis',
    'services.ai.title': 'AI Integration',
    'services.analytics.title': 'Data Analytics',
    'services.analytics.desc': 'We transform complex data into actionable insights that drive strategic decision-making.',
    'services.automation.desc': 'We optimize repetitive and manual tasks to free up valuable time for your team, reduce errors and improve operational efficiency.',
    'services.visualization.desc': 'We transform complex data into interactive visualizations and dashboards that facilitate understanding and effective decision making.',
    'services.extraction.desc': 'We extract, transform and clean data from multiple sources to convert it into valuable and actionable information for your business.',
    'services.consulting.desc': 'We advise and develop strategies to implement a data-driven culture in your organization, identifying key KPIs and improvement opportunities.',
    'services.training.desc': 'Personalized training programs for your team to develop analytical skills and make the most of available tools.',
    'services.unstructured.desc': 'We extract valuable insights from texts, images and communications through advanced processing and intelligent analysis techniques.',
    'services.ai.desc': 'We implement personalized artificial intelligence solutions that automate complex processes and improve your company\'s predictive capacity.',
    'process.category': 'OUR METHODOLOGY',
    'process.title': 'Work Process',
    'process.subtitle': 'We follow a structured but flexible approach that guarantees optimal results in each project.',
    'process.step1.title': 'Diagnosis',
    'process.step1.desc': 'We analyze your current situation, identify opportunities and define clear objectives.',
    'process.step2.title': 'Design',
    'process.step2.desc': 'We develop a personalized strategy and plan the optimal solution for your needs.',
    'process.step3.title': 'Implementation',
    'process.step3.desc': 'We execute the solution with an agile approach, allowing adjustments during the process.',
    'process.step4.title': 'Optimization',
    'process.step4.desc': 'We monitor results, refine the solution and guarantee knowledge transfer.',
    'process.diagram.title': 'Workflow',
    'process.diagram.subtitle': 'An iterative and adaptive process to maximize the value of your data.',
    'about.title': 'Why choose DataSmart',
    'about.experience': 'Proven Experience',
    'about.experience.desc': 'Years of experience helping companies of all sizes harness the power of their data.',
    'about.innovation': 'Constant Innovation',
    'about.innovation.desc': 'We use the latest technologies and methodologies to deliver cutting-edge solutions.',
    'about.results': 'Measurable Results',
    'about.results.desc': 'We focus on generating real and measurable impact on our clients\' key indicators.',
    'contact.title': 'Start your digital transformation',
    'contact.subtitle': 'Contact us for a free consultation and discover how we can help your company.',
    'contact.cta': 'Contact now',
    'stats.projects': 'Completed Projects',
    'stats.clients': 'Satisfied Clients',
    'stats.efficiency': 'Efficiency Improvement',
    'stats.roi': 'Average ROI',
    'why_us.category': 'WHY CHOOSE US',
    'why_us.title': 'Our Differentiated Approach',
    'why_us.subtitle': 'We combine technical expertise with a deep understanding of business to deliver solutions that generate real and measurable impact.',
    'why_us.scalable.title': 'Scalable Solutions',
    'why_us.scalable.desc': 'Our solutions grow with your business, adapting to your current and future needs without requiring constant reinvestment.',
    'why_us.integral.title': 'Integral Approach',
    'why_us.integral.desc': 'We combine data, technology and business strategy to deliver complete solutions that generate immediate and sustainable value.',
    'why_us.processing.title': 'Intelligent Processing',
    'why_us.processing.desc': 'Specialists in extracting value from multiple formats (text, image, audio, video) using advanced AI technologies.',
    'why_us.development.title': 'Custom Development',
    'why_us.development.desc': 'We create interactive applications with modern technologies like React/Next.js specifically adapted to your needs and workflows.',
    'why_us.support.title': 'Continuous Support',
    'why_us.support.desc': 'We not only implement solutions, but accompany you throughout the process, ensuring adoption and maximizing return on investment.',
    'why_us.results.title': 'Measurable Results',
    'why_us.results.desc': 'We define clear KPIs for each project, guaranteeing tangible results and a quantifiable return on investment from the start.'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};