import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  es: {
    'company.name': 'DataSmart',
    'company.tagline': 'Transformando datos en decisiones inteligentes',
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'fullscreen.enter': 'Pantalla completa',
    'fullscreen.exit': 'Salir de pantalla completa',
    'fullscreen.error': 'Error al entrar en pantalla completa:',
    'hero.category': 'ANÁLISIS DE DATOS Y AUTOMATIZACIÓN',
    'hero.title': 'Transformamos tus datos en decisiones inteligentes',
    'hero.subtitle': 'Ofrecemos soluciones personalizadas de análisis de datos y automatización adaptadas a tu negocio, ayudándote a optimizar procesos, reducir costos y mejorar la toma de decisiones.',
    'hero.cta': 'Conoce nuestros servicios',
    'hero.dashboard.title': 'Panel de Análisis',
    'hero.dashboard.live_data': 'Datos en Vivo',
    'hero.dashboard.data_processing': 'Procesamiento de Datos',
    'hero.dashboard.processing_active': 'Activo',
    'hero.dashboard.realtime_analytics': 'Análisis en Tiempo Real',
    'hero.dashboard.analytics_running': 'Ejecutándose',
    'hero.dashboard.data_accuracy': 'Precisión de Datos',
    'hero.dashboard.key_metrics': 'Métricas Clave',
    'hero.dashboard.response': 'Respuesta',
    'hero.dashboard.records': 'Registros',
    'hero.dashboard.uptime': 'Tiempo Activo',
    'hero.robot.greeting': '¡Hola! ¿Te ayudo con tus datos? 🤖💙',
    'market.category': 'OPORTUNIDAD DE MERCADO',
    'market.title': 'Cómo Diferentes Empresas Aprovechan sus Datos',
    'market.subtitle': 'Cada tipo de organización tiene oportunidades únicas para transformar datos en ventaja competitiva. Descubre cómo implementamos soluciones personalizadas según las necesidades específicas de tu sector.',
    'market.intro': 'Identificamos las principales formas en que diferentes empresas pueden aprovechar sus datos para impulsar el crecimiento y la eficiencia.',
    'market.pymes.title': 'Pequeñas y Medianas Empresas',
    'market.pymes.desc': 'Optimizan inventarios, identifican patrones de ventas estacionales, automatizan reportes financieros y mejoran la experiencia del cliente mediante análisis de comportamiento de compra.',
    'market.pymes.solution': 'Dashboards intuitivos, alertas automáticas de inventario y análisis de rentabilidad por producto.',
    'market.startups.title': 'Startups Tecnológicas',
    'market.startups.desc': 'Validan hipótesis de mercado con datos reales, optimizan embudos de conversión, analizan métricas de retención de usuarios y toman decisiones ágiles basadas en evidencia.',
    'market.startups.solution': 'Analytics en tiempo real, métricas de crecimiento y herramientas de experimentación A/B.',
    'market.growing.title': 'Empresas en Expansión',
    'market.growing.desc': 'Integran datos de múltiples sucursales, predicen demanda regional, optimizan cadenas de suministro y mantienen calidad de servicio durante el crecimiento.',
    'market.growing.solution': 'Sistemas escalables, inteligencia de negocios centralizada y análisis predictivo.',
    'market.departments.title': 'Departamentos Corporativos',
    'market.departments.desc': 'Unifican datos de Marketing, Ventas y Operaciones para crear una vista 360° del negocio, optimizan campañas y mejoran la colaboración interdepartamental.',
    'market.departments.solution': 'Integración de sistemas existentes, reportes unificados y análisis de atribución.',
    'market.ngos.title': 'Organizaciones sin Fines de Lucro',
    'market.ngos.desc': 'Miden impacto social cuantificable, optimizan programas de ayuda, mejoran transparencia con donantes y maximizan eficiencia en distribución de recursos.',
    'market.ngos.solution': 'Reportes de impacto visual, seguimiento de beneficiarios y análisis de eficiencia.',
    'market.acronyms': 'Cada sector requiere un enfoque único para maximizar el valor de sus datos específicos.',
    
    // Casos de uso de automatización
    'automation.case.category': 'CASOS DE USO - AUTOMATIZACIÓN',
    'automation.case.problem.title': 'El Problema',
    'automation.case.problem.desc': 'Las tareas manuales repetitivas consumen tiempo valioso que podría orientarse a labores estratégicas. Gran parte del tiempo de trabajo se destina a procesos manuales como:',
    'automation.case.problem.tasks': 'Transcribir datos entre sistemas • Elaborar y formatear reportes periódicos • Procesar documentos (facturas, pedidos) • Monitorear manualmente métricas clave',
    'automation.case.solution.title': 'Solución General',
    'automation.case.solution.desc': 'Implementar flujos automáticos y herramientas de software que extraigan, consoliden y actualicen información sin intervención manual o con la mínima necesaria.',
    
    // Caso PYME Básico
    'automation.pyme.basic.title': 'PYME - Automatización de Reportes',
    'automation.pyme.basic.subtitle': 'Caso de Negocio: Consultora con Reportes Gerenciales',
    'automation.pyme.basic.challenge': 'El Desafío',
    'automation.pyme.basic.challenge.desc': 'Una consultora tiene un asistente administrativo que invierte tiempo considerable generando reportes gerenciales sobre horas facturables y proyectos. Este proceso manual es propenso a errores y retrasa la toma de decisiones.',
    'automation.pyme.basic.solution': 'Nuestra Solución',
    'automation.pyme.basic.solution.desc': 'Pipeline automatizado que extrae datos del sistema de proyectos y genera reportes con KPIs estandarizados. Incluye alertas automáticas y visualizaciones interactivas.',
    'automation.pyme.basic.benefits': 'Beneficios Obtenidos',
    'automation.pyme.basic.benefits.desc': 'Ahorro significativo de tiempo mensual, reducción drástica de errores y mayor rapidez en la identificación de desviaciones. El equipo puede enfocarse en actividades de mayor valor.',
    
    // Caso PYME Intermedio
    'automation.pyme.intermediate.title': 'PYME - Sistema Financiero Automatizado',
    'automation.pyme.intermediate.subtitle': 'Caso de Negocio: Empresa de Servicios con Consolidación Financiera',
    'automation.pyme.intermediate.challenge': 'El Desafío',
    'automation.pyme.intermediate.challenge.desc': 'Empresa de servicios donde el contador dedica varios días al mes consolidando información financiera de múltiples fuentes, causando retrasos en la visibilidad financiera.',
    'automation.pyme.intermediate.solution': 'Nuestra Solución',
    'automation.pyme.intermediate.solution.desc': 'Tablero integrado que conecta automáticamente datos bancarios y de facturación. Incluye alertas de flujo de caja y reportes financieros automatizados.',
    'automation.pyme.intermediate.benefits': 'Beneficios Obtenidos',
    'automation.pyme.intermediate.benefits.desc': 'Reducción significativa del tiempo de preparación, visibilidad diaria de la situación financiera y detección temprana de problemas de flujo de caja.',
    
    // Caso Startup Intermedio
    'automation.startup.intermediate.title': 'Startup - Reportes para Inversores',
    'automation.startup.intermediate.subtitle': 'Caso de Negocio: Startup con Reportes Mensuales para Inversionistas',
    'automation.startup.intermediate.challenge': 'El Desafío',
    'automation.startup.intermediate.challenge.desc': 'Startup que requiere informes mensuales para inversionistas donde el CEO y CMO dedican días completos a recopilar y formatear datos de múltiples plataformas.',
    'automation.startup.intermediate.solution': 'Nuestra Solución',
    'automation.startup.intermediate.solution.desc': 'Sistema que consolida automáticamente métricas de diversas plataformas (analytics, CRM, finanzas) y genera reportes profesionales con gráficos interactivos.',
    'automation.startup.intermediate.benefits': 'Beneficios Obtenidos',
    'automation.startup.intermediate.benefits.desc': 'Reducción drástica del tiempo de preparación, estandarización de métricas y mejora en la comunicación con inversores.',
    
    // Caso Startup Avanzado
    'automation.startup.advanced.title': 'Startup - Sistema Integral de Métricas',
    'automation.startup.advanced.subtitle': 'Caso de Negocio: Startup en Crecimiento con Múltiples Departamentos',
    'automation.startup.advanced.challenge': 'El Desafío',
    'automation.startup.advanced.challenge.desc': 'Startup en fase de crecimiento con 4 áreas (marketing, ventas, producto, finanzas) que dedican tiempo excesivo en informes cruzados, causando desalineación entre equipos.',
    'automation.startup.advanced.solution': 'Nuestra Solución',
    'automation.startup.advanced.solution.desc': 'Plataforma integral que integra todas las fuentes de datos, automatiza cálculos complejos y facilita la distribución inteligente de información entre departamentos.',
    'automation.startup.advanced.benefits': 'Beneficios Obtenidos',
    'automation.startup.advanced.benefits.desc': 'Visibilidad en tiempo real de métricas clave, mejor alineación entre equipos y capacidad de respuesta ágil ante desviaciones.',
    
    // Caso Empresa en Crecimiento
    'automation.growing.advanced.title': 'Empresa en Crecimiento - Procesos Interdepartamentales',
    'automation.growing.advanced.subtitle': 'Caso de Negocio: Empresa Manufacturera con Coordinación Compleja',
    'automation.growing.advanced.challenge': 'El Desafío',
    'automation.growing.advanced.challenge.desc': 'Empresa manufacturera donde la coordinación manual entre ventas, producción y logística causa demoras significativas en la entrega de pedidos y pérdida de trazabilidad.',
    'automation.growing.advanced.solution': 'Nuestra Solución',
    'automation.growing.advanced.solution.desc': 'Sistema que orquesta automáticamente el flujo completo desde el pedido hasta la entrega, incluyendo planificación de producción y optimización logística.',
    'automation.growing.advanced.benefits': 'Beneficios Obtenidos',
    'automation.growing.advanced.benefits.desc': 'Reducción significativa en tiempos de procesamiento, trazabilidad completa del ciclo de venta y mejora en la satisfacción del cliente.',
    
    // Caso Departamento Corporativo
    'automation.corporate.premium.title': 'Corporativo - Inteligencia Competitiva',
    'automation.corporate.premium.subtitle': 'Caso de Negocio: Departamento de Estrategia con Monitoreo de Competencia',
    'automation.corporate.premium.challenge': 'El Desafío',
    'automation.corporate.premium.challenge.desc': 'Departamento de estrategia con múltiples analistas que invierten la mayor parte de su tiempo monitoreando competidores y tendencias de mercado de forma manual.',
    'automation.corporate.premium.solution': 'Nuestra Solución',
    'automation.corporate.premium.solution.desc': 'Plataforma de inteligencia que captura, filtra y analiza automáticamente información de múltiples fuentes, generando insights estratégicos y alertas tempranas.',
    'automation.corporate.premium.benefits': 'Beneficios Obtenidos',
    'automation.corporate.premium.benefits.desc': 'Reasignación de talento a tareas más estratégicas, detección temprana de amenazas y oportunidades, y ventaja competitiva sostenible.',
    
    'services.title': 'Nuestros Servicios',
    'services.what_we_offer': 'Qué ofrecemos',
    'services.subtitle': 'Desarrollamos soluciones a medida que permiten aprovechar al máximo el valor de tus datos, desde la automatización de procesos hasta la visualización avanzada.',
    'services.automation.title': 'Automatización de Procesos',
    'services.automation.subtitle': 'Transformamos tareas repetitivas y manuales en flujos automatizados inteligentes para liberar el potencial de tu equipo, reducir errores y maximizar la eficiencia operativa.',
    'services.automation.benefits.efficiency': 'Mayor Eficiencia',
    'services.automation.benefits.accuracy': 'Menor Errores',
    'services.automation.benefits.time': 'Ahorro de Tiempo',
    'services.automation.problems.title': 'Problemas que Resolvemos',
    'services.automation.problems.data_transfer': 'Transcribir datos entre sistemas',
    'services.automation.problems.reports': 'Elaborar y formatear reportes periódicos',
    'services.automation.problems.documents': 'Procesar documentos (facturas, pedidos)',
    'services.automation.problems.monitoring': 'Monitorear manualmente métricas clave',
    'services.automation.problems.outdated_info': 'No disponibilidad de información actualizada',
    'services.visualization.title': 'Visualización de Datos',
    'services.visualization.subtitle': 'Transformamos datos complejos en visualizaciones interactivas y dashboards que facilitan la comprensión y toma de decisiones efectivas.',
    'services.visualization.benefits.clarity': 'Mayor Claridad',
    'services.visualization.benefits.insights': 'Insights Rápidos',
    'services.visualization.benefits.decisions': 'Mejores Decisiones',
    'services.visualization.opportunities.title': 'Oportunidades que Brindamos',
    'services.visualization.opportunities.dashboards': 'Dashboards interactivos en tiempo real',
    'services.visualization.opportunities.kpis': 'Monitoreo visual de KPIs críticos',
    'services.visualization.opportunities.trends': 'Identificación de patrones y tendencias',
    'services.visualization.opportunities.alerts': 'Alertas visuales automáticas',
    'services.visualization.opportunities.storytelling': 'Storytelling con datos para presentaciones',
    'services.extraction.title': 'Extracción y Procesamiento',
    'services.extraction.subtitle': 'Extraemos, transformamos y unificamos datos de múltiples fuentes para convertirlos en información valiosa y accionable.',
    'services.extraction.benefits.web': 'Datos desde sitios web',
    'services.extraction.benefits.db': 'Bases de datos de varios tipos',
    'services.extraction.benefits.integration': 'Integración con sistemas',
    'services.extraction.opportunities.title': 'Oportunidades que Brindamos',
    'services.extraction.opportunities.web': 'Obtención de información de sitios web públicos y privados',
    'services.extraction.opportunities.db': 'Extracción y migración de datos entre bases de datos SQL, NoSQL y APIs',
    'services.extraction.opportunities.integration': 'Integración de datos con ERPs, CRMs y otras plataformas',
    'services.extraction.opportunities.pipeline': 'Automatización de pipelines de datos',
    'services.extraction.opportunities.cleaning': 'Unificación, limpieza y enriquecimiento de datos',
    'services.consulting.title': 'Consultoría en Análisis',
    'services.training.title': 'Formación y Capacitación',
    'services.unstructured.title': 'Análisis de Datos No Estructurados',
    'services.ai.title': 'Integración con IA',
    'services.analytics.title': 'Análisis de Datos',
    'services.analytics.desc': 'Transformamos datos complejos en insights accionables que impulsan la toma de decisiones estratégicas.',
    'services.automation.desc': 'Optimizamos tareas repetitivas y manuales para liberar tiempo valioso de tu equipo, reducir errores y mejorar la eficiencia operativa.',
    'services.visualization.desc': 'Transformamos datos complejos en visualizaciones interactivas y dashboards que facilitan la comprensión y toma de decisiones efectivas.',
    'services.extraction.desc': 'Extraemos, transformamos y limpiamos datos de múltiples fuentes para convertirlos en información valiosa y accionable para tu negocio.',
    'services.consulting.desc': 'Asesoramos y desarrollamos estrategias para implementar una cultura data-driven en tu organización, identificando KPIs clave y oportunidades de mejora.',
    'services.training.desc': 'Programas de formación personalizados para que tu equipo desarrolle habilidades analíticas y aproveche al máximo las herramientas disponibles.',
    'services.unstructured.desc': 'Extraemos insights valiosos de textos, imágenes y comunicaciones mediante técnicas avanzadas de procesamiento y análisis inteligente.',
    'services.ai.desc': 'Implementamos soluciones de inteligencia artificial personalizadas que automatizan procesos complejos y mejoran la capacidad predictiva de tu empresa.',
    'process.category': 'NUESTRA METODOLOGÍA',
    'process.title': 'Proceso de Trabajo',
    'process.subtitle': 'Seguimos un enfoque estructurado pero flexible que garantiza resultados óptimos en cada proyecto.',
    'process.step1.title': 'Diagnóstico',
    'process.step1.desc': 'Analizamos tu situación actual, identificamos oportunidades y definimos objetivos claros.',
    'process.step2.title': 'Diseño',
    'process.step2.desc': 'Desarrollamos una estrategia personalizada y planificamos la solución óptima para tus necesidades.',
    'process.step3.title': 'Implementación',
    'process.step3.desc': 'Ejecutamos la solución con un enfoque ágil, permitiendo ajustes durante el proceso.',
    'process.step4.title': 'Optimización',
    'process.step4.desc': 'Monitorizamos resultados, refinamos la solución y garantizamos la transferencia de conocimiento.',
    'process.diagram.title': 'Flujo de Trabajo',
    'process.diagram.subtitle': 'Un proceso iterativo y adaptativo para maximizar el valor de tus datos.',
    'about.title': 'Por qué elegir DataSmart',
    'about.experience': 'Experiencia Comprobada',
    'about.experience.desc': 'Años de experiencia ayudando a empresas de todos los tamaños a aprovechar el poder de sus datos.',
    'about.innovation': 'Innovación Constante',
    'about.innovation.desc': 'Utilizamos las últimas tecnologías y metodologías para entregar soluciones de vanguardia.',
    'about.results': 'Resultados Medibles',
    'about.results.desc': 'Nos enfocamos en generar impacto real y medible en los indicadores clave de nuestros clientes.',
    'contact.title': 'Comienza tu transformación digital',
    'contact.subtitle': 'Contáctanos para una consulta gratuita y descubre cómo podemos ayudar a tu empresa.',
    'contact.cta': 'Contactar ahora',
    'stats.projects': 'Proyectos Completados',
    'stats.clients': 'Clientes Satisfechos',
    'stats.efficiency': 'Mejora en Eficiencia',
    'stats.roi': 'ROI Promedio',
    'why_us.category': 'POR QUÉ ELEGIRNOS',
    'why_us.title': 'Nuestro Enfoque Diferenciado',
    'why_us.subtitle': 'Combinamos expertise técnico con un profundo entendimiento del negocio para ofrecer soluciones que generan impacto real y medible.',
    'why_us.scalable.title': 'Soluciones Escalables',
    'why_us.scalable.desc': 'Nuestras soluciones crecen con tu negocio, adaptándose a tus necesidades actuales y futuras sin necesidad de reinversiones constantes.',
    'why_us.integral.title': 'Enfoque Integral',
    'why_us.integral.desc': 'Combinamos datos, tecnología y estrategia de negocio para ofrecer soluciones completas que generan valor inmediato y sostenible.',
    'why_us.processing.title': 'Procesamiento Inteligente',
    'why_us.processing.desc': 'Especialistas en extraer valor de múltiples formatos (texto, imagen, audio, video) mediante tecnologías avanzadas de IA.',
    'why_us.development.title': 'Desarrollo a Medida',
    'why_us.development.desc': 'Creamos aplicaciones interactivas con tecnologías modernas como React/Next.js adaptadas específicamente a tus necesidades y flujos de trabajo.',
    'why_us.support.title': 'Acompañamiento Continuo',
    'why_us.support.desc': 'No solo implementamos soluciones, sino que te acompañamos en todo el proceso, asegurando adopción y maximizando el retorno de inversión.',
    'why_us.results.title': 'Resultados Medibles',
    'why_us.results.desc': 'Definimos KPIs claros para cada proyecto, garantizando resultados tangibles y un retorno de inversión cuantificable desde el inicio.',
    'services.unstructured.opportunities.nlp': 'Procesamiento de Lenguaje Natural (NLP)',
    'services.unstructured.opportunities.documents': 'Análisis de Documentos',
    'services.unstructured.opportunities.images_video': 'Imágenes y Video',
    'services.unstructured.opportunities.geo': 'Datos Geoespaciales',
    'services.unstructured.opportunities.social': 'Datos de Redes Sociales',
    'services.unstructured.opportunities.audio': 'Procesamiento de Audio',
    'services.unstructured.benefits.text': 'Procesamiento de textos',
    'services.unstructured.benefits.image': 'Análisis de imágenes',
    'services.unstructured.benefits.communication': 'Mensajería y comunicaciones',
    'services.ai.benefits.automation': 'Automatización inteligente',
    'services.ai.benefits.prediction': 'Predicción avanzada',
    'services.ai.benefits.integration': 'Integración con sistemas',
    'services.ai.opportunities.chatbots': 'Chatbots y asistentes virtuales personalizados',
    'services.ai.opportunities.prediction': 'Análisis predictivo y recomendaciones automáticas',
    'services.ai.opportunities.security': 'Automatización de seguridad y detección de fraudes',
    'services.ai.opportunities.optimization': 'Optimización de procesos mediante IA',
    'use_case': 'Caso de Uso',
    'unstructured_data_analysis': 'Análisis de Datos No Estructurados',
    'opportunities_we_provide': 'Oportunidades que Brindamos',
    
    // Casos de uso específicos hardcodeados
    'use_case.accounting_api.title': 'Integración Contable con API - Reportes Automáticos',
    'use_case.accounting_api.subtitle': 'Procesamiento automático de datos contables para dashboards en tiempo real',
    'use_case.quotation_system.title': 'Sistema de Cotizaciones Automáticas',
    'use_case.quotation_system.subtitle': 'Generación inteligente de propuestas comerciales personalizadas',
    'use_case.sales_tracking.title': 'Sistema de Seguimiento para Vendedores',
    'use_case.sales_tracking.subtitle': 'Monitoreo inteligente del desempeño comercial y pipeline de ventas',
    'use_case.communication_classification.title': 'Clasificación Inteligente de Comunicaciones',
    'use_case.communication_classification.subtitle': 'Análisis automático de correos y comentarios de redes sociales',
    'use_case.chatbot_proposals.title': 'Chatbots Internos para Generación de Propuestas',
    'use_case.chatbot_proposals.subtitle': 'Asistente IA para mejora del performance del equipo comercial',
    'use_case.inventory_management.title': 'Sistema de Gestión de Inventarios con Alertas',
    'use_case.inventory_management.subtitle': 'Control inteligente de stock con predicción de demanda',
    
    // Secciones comunes de casos de uso
    'use_case.challenge': 'El Desafío',
    'use_case.solution': 'Nuestra Solución',
    'use_case.benefits': 'Beneficios Obtenidos',
    
    // Contenido específico de cada caso de uso
    'use_case.accounting_api.challenge.desc': 'Información financiera dispersa en diferentes sistemas contables, reportes manuales que consumen tiempo y son propensos a errores.',
    'use_case.accounting_api.solution.desc': 'Integración directa con API del software contable, procesamiento automático y generación de dashboards con KPIs en tiempo real.',
    'use_case.accounting_api.benefits.desc': 'Visibilidad completa de utilidades, cartera, flujo de caja, comisiones y KPIs financieros actualizados automáticamente.',
    
    'use_case.quotation_system.challenge.desc': 'Proceso manual lento para generar cotizaciones, inconsistencias en precios y tiempo excesivo de respuesta a clientes.',
    'use_case.quotation_system.solution.desc': 'Sistema inteligente que genera cotizaciones personalizadas automáticamente basado en parámetros del cliente y histórico de ventas.',
    'use_case.quotation_system.benefits.desc': 'Reducción del 90% en tiempo de cotización, consistencia en precios y mejora en tasa de conversión de clientes.',
    
    'use_case.sales_tracking.challenge.desc': 'Falta de visibilidad en el pipeline de ventas, seguimiento manual de prospectos y dificultad para identificar oportunidades.',
    'use_case.sales_tracking.solution.desc': 'Dashboard de seguimiento automático con alertas, métricas de desempeño y predicciones de cierre de ventas.',
    'use_case.sales_tracking.benefits.desc': 'Aumento del 35% en conversión de leads, mejor gestión del tiempo comercial y identificación temprana de oportunidades.',
    
    'use_case.communication_classification.challenge.desc': 'Volumen alto de correos y comentarios, clasificación manual lenta y pérdida de mensajes importantes o urgentes.',
    'use_case.communication_classification.solution.desc': 'IA que clasifica automáticamente correos y comentarios por urgencia, sentimiento y categoría, con alertas inteligentes.',
    'use_case.communication_classification.benefits.desc': 'Reducción del 80% en tiempo de clasificación, respuesta más rápida a urgencias y mejor seguimiento de la satisfacción del cliente.',
    
    'use_case.chatbot_proposals.challenge.desc': 'Equipos comerciales con acceso limitado a información técnica y dificultad para crear propuestas consistentes y competitivas.',
    'use_case.chatbot_proposals.solution.desc': 'Chatbot interno entrenado con datos de la empresa que asiste al equipo comercial en la creación de propuestas personalizadas.',
    'use_case.chatbot_proposals.benefits.desc': 'Mejora del 50% en calidad de propuestas, reducción del tiempo de preparación y estandarización de procesos comerciales.',
    
    'use_case.inventory_management.challenge.desc': 'Control manual de inventarios, falta de alertas automáticas y dificultad para predecir demanda futura.',
    'use_case.inventory_management.solution.desc': 'Sistema automatizado con alertas de stock mínimo, predicción de demanda y optimización automática de pedidos.',
    'use_case.inventory_management.benefits.desc': 'Reducción del 25% en costos de inventario, eliminación de roturas de stock y mejora en la planificación de compras.',
    
    // Sección de formación y capacitación
    'training.description': 'Programas personalizados para que tu equipo desarrolle habilidades analíticas y aproveche al máximo herramientas como Excel, Power BI, Tableau y soluciones de IA para potenciar el análisis de datos.',
    'training.excel_powerbi_tableau': 'Excel, Power BI y Tableau',
    'training.ai_analysis': 'IA aplicada al análisis',
    'training.performance_improvement': 'Mejora de performance analítico',
    'training.opportunities.excel_training': 'Capacitación en Excel, Power BI y Tableau desde nivel básico a avanzado',
    'training.opportunities.ai_tools': 'Uso de herramientas de IA para acelerar el análisis y la toma de decisiones',
    'training.opportunities.workshops': 'Workshops prácticos y resolución de casos reales',
    'training.opportunities.best_practices': 'Implementación de mejores prácticas en procesos y análisis de datos',
    'training.opportunities.performance_boost': 'Aumento del performance y productividad del equipo',
    
    // Slide introductorio de casos de uso
    'use_cases_intro.category': 'CASOS DE USO REALES',
    'use_cases_intro.title': 'Casos de Éxito',
    'use_cases_intro.subtitle': 'Descubre cómo hemos ayudado a empresas como la tuya',
    'use_cases_intro.description': 'Estos son ejemplos reales de cómo nuestras soluciones han transformado los procesos de nuestros clientes, generando resultados medibles y mejorando su eficiencia operativa.',
    'use_cases_intro.next_slides': 'A continuación, te presentamos casos específicos organizados por tipo de solución',
    'use_cases_intro.accounting': 'Integración Contable',
    'use_cases_intro.quotations': 'Cotizaciones Automáticas',
    'use_cases_intro.sales_tracking': 'Seguimiento Comercial',
    'use_cases_intro.ai_classification': 'Clasificación IA',
    'use_cases_intro.chatbots': 'Chatbots Internos',
    'use_cases_intro.inventory': 'Gestión de Inventarios',
    'final_leverage.title': 'Cómo Diferentes Empresas Aprovechan sus Datos',
    'final_leverage.subtitle': 'Inspírate con ejemplos reales de transformación y crecimiento impulsados por el análisis de datos.'
  },
  en: {
    'company.name': 'DataSmart',
    'company.tagline': 'Transforming data into smart decisions',
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'fullscreen.enter': 'Full screen',
    'fullscreen.exit': 'Exit full screen',
    'fullscreen.error': 'Error entering full screen:',
    'hero.category': 'DATA ANALYSIS AND AUTOMATION',
    'hero.title': 'We transform your data into smart decisions',
    'hero.subtitle': 'We offer personalized data analysis and automation solutions tailored to your business, helping you optimize processes, reduce costs and improve decision making.',
    'hero.cta': 'Learn about our services',
    'hero.dashboard.title': 'Analytics Dashboard',
    'hero.dashboard.live_data': 'Live Data',
    'hero.dashboard.data_processing': 'Data Processing',
    'hero.dashboard.processing_active': 'Active',
    'hero.dashboard.realtime_analytics': 'Real-time Analytics',
    'hero.dashboard.analytics_running': 'Running',
    'hero.dashboard.data_accuracy': 'Data Accuracy',
    'hero.dashboard.key_metrics': 'Key Metrics',
    'hero.dashboard.response': 'Response',
    'hero.dashboard.records': 'Records',
    'hero.dashboard.uptime': 'Uptime',
    'hero.robot.greeting': 'Hello! Can I help you with your data? 🤖💙',
    'market.category': 'MARKET OPPORTUNITY',
    'market.title': 'How Different Companies Leverage Their Data',
    'market.subtitle': 'Each type of organization has unique opportunities to transform data into competitive advantage. Discover how we implement personalized solutions according to your sector\'s specific needs.',
    'market.intro': 'We identify the main ways different companies can leverage their data to drive growth and efficiency.',
    'market.pymes.title': 'Small and Medium Enterprises',
    'market.pymes.desc': 'Optimize inventory, identify seasonal sales patterns, automate financial reporting, and improve customer experience through purchase behavior analysis.',
    'market.pymes.solution': 'Intuitive dashboards, automatic inventory alerts, and product profitability analysis.',
    'market.startups.title': 'Technology Startups',
    'market.startups.desc': 'Validate market hypotheses with real data, optimize conversion funnels, analyze user retention metrics, and make agile evidence-based decisions.',
    'market.startups.solution': 'Real-time analytics, growth metrics, and A/B testing tools.',
    'market.growing.title': 'Expanding Companies',
    'market.growing.desc': 'Integrate data from multiple branches, predict regional demand, optimize supply chains, and maintain service quality during growth.',
    'market.growing.solution': 'Scalable systems, centralized business intelligence, and predictive analysis.',
    'market.departments.title': 'Corporate Departments',
    'market.departments.desc': 'Unify Marketing, Sales, and Operations data to create a 360° business view, optimize campaigns, and improve interdepartmental collaboration.',
    'market.departments.solution': 'Integration of existing systems, unified reports, and attribution analysis.',
    'market.ngos.title': 'Non-Profit Organizations',
    'market.ngos.desc': 'Measure quantifiable social impact, optimize aid programs, improve donor transparency, and maximize efficiency in resource distribution.',
    'market.ngos.solution': 'Visual impact reports, beneficiary tracking, and efficiency analysis.',
    'market.acronyms': 'Each sector requires a unique approach to maximize the value of its specific data.',
    
    // Automation use cases
    'automation.case.category': 'USE CASES - AUTOMATION',
    'automation.case.problem.title': 'The Problem',
    'automation.case.problem.desc': 'Repetitive manual tasks consume valuable time that could be oriented towards strategic work. Much of work time is dedicated to manual processes such as:',
    'automation.case.problem.tasks': 'Transcribing data between systems • Creating and formatting periodic reports • Processing documents (invoices, orders) • Manually monitoring key metrics',
    'automation.case.solution.title': 'General Solution',
    'automation.case.solution.desc': 'Implement automatic workflows and software tools that extract, consolidate and update information without manual intervention or with minimal necessary intervention.',
    
    // Basic SME Case
    'automation.pyme.basic.title': 'SME - Report Automation',
    'automation.pyme.basic.subtitle': 'Business Case: Consulting Firm with Management Reports',
    'automation.pyme.basic.challenge': 'The Challenge',
    'automation.pyme.basic.challenge.desc': 'A consulting firm has an administrative assistant who invests considerable time generating management reports on billable hours and projects. This manual process is error-prone and delays decision making.',
    'automation.pyme.basic.solution': 'Our Solution',
    'automation.pyme.basic.solution.desc': 'Automated pipeline that extracts data from the project system and generates reports with standardized KPIs. Includes automatic alerts and interactive visualizations.',
    'automation.pyme.basic.benefits': 'Benefits Obtained',
    'automation.pyme.basic.benefits.desc': 'Significant monthly time savings, drastic error reduction and faster identification of deviations. The team can focus on higher-value activities.',
    
    // Intermediate SME Case
    'automation.pyme.intermediate.title': 'SME - Automated Financial System',
    'automation.pyme.intermediate.subtitle': 'Business Case: Service Company with Financial Consolidation',
    'automation.pyme.intermediate.challenge': 'The Challenge',
    'automation.pyme.intermediate.challenge.desc': 'Service company where the accountant spends several days a month consolidating financial information from multiple sources, causing delays in financial visibility.',
    'automation.pyme.intermediate.solution': 'Our Solution',
    'automation.pyme.intermediate.solution.desc': 'Integrated dashboard that automatically connects banking and billing data. Includes cash flow alerts and automated financial reports.',
    'automation.pyme.intermediate.benefits': 'Benefits Obtained',
    'automation.pyme.intermediate.benefits.desc': 'Significant reduction in preparation time, daily visibility of financial situation and early detection of cash flow problems.',
    
    // Intermediate Startup Case
    'automation.startup.intermediate.title': 'Startup - Investor Reports',
    'automation.startup.intermediate.subtitle': 'Business Case: Startup with Monthly Investor Reports',
    'automation.startup.intermediate.challenge': 'The Challenge',
    'automation.startup.intermediate.challenge.desc': 'Startup that requires monthly reports for investors where CEO and CMO spend full days collecting and formatting data from multiple platforms.',
    'automation.startup.intermediate.solution': 'Our Solution',
    'automation.startup.intermediate.solution.desc': 'System that automatically consolidates metrics from various platforms (analytics, CRM, finance) and generates professional reports with interactive charts.',
    'automation.startup.intermediate.benefits': 'Benefits Obtained',
    'automation.startup.intermediate.benefits.desc': 'Drastic reduction in preparation time, standardization of metrics and improvement in investor communication.',
    
    // Advanced Startup Case
    'automation.startup.advanced.title': 'Startup - Comprehensive Metrics System',
    'automation.startup.advanced.subtitle': 'Business Case: Growing Startup with Multiple Departments',
    'automation.startup.advanced.challenge': 'The Challenge',
    'automation.startup.advanced.challenge.desc': 'Growing startup with 4 areas (marketing, sales, product, finance) that spend excessive time on cross-reports, causing team misalignment.',
    'automation.startup.advanced.solution': 'Our Solution',
    'automation.startup.advanced.solution.desc': 'Comprehensive platform that integrates all data sources, automates complex calculations and facilitates intelligent information distribution between departments.',
    'automation.startup.advanced.benefits': 'Benefits Obtained',
    'automation.startup.advanced.benefits.desc': 'Real-time visibility of key metrics, better team alignment and agile response capability to deviations.',
    
    // Growing Company Case
    'automation.growing.advanced.title': 'Growing Company - Interdepartmental Processes',
    'automation.growing.advanced.subtitle': 'Business Case: Manufacturing Company with Complex Coordination',
    'automation.growing.advanced.challenge': 'The Challenge',
    'automation.growing.advanced.challenge.desc': 'Manufacturing company where manual coordination between sales, production and logistics causes significant delays in order delivery and loss of traceability.',
    'automation.growing.advanced.solution': 'Our Solution',
    'automation.growing.advanced.solution.desc': 'System that automatically orchestrates the complete flow from order to delivery, including production planning and logistics optimization.',
    'automation.growing.advanced.benefits': 'Benefits Obtained',
    'automation.growing.advanced.benefits.desc': 'Significant reduction in processing times, complete sales cycle traceability and improvement in customer satisfaction.',
    
    // Corporate Department Case
    'automation.corporate.premium.title': 'Corporate - Competitive Intelligence',
    'automation.corporate.premium.subtitle': 'Business Case: Strategy Department with Competition Monitoring',
    'automation.corporate.premium.challenge': 'The Challenge',
    'automation.corporate.premium.challenge.desc': 'Strategy department with multiple analysts who invest most of their time manually monitoring competitors and market trends.',
    'automation.corporate.premium.solution': 'Our Solution',
    'automation.corporate.premium.solution.desc': 'Intelligence platform that automatically captures, filters and analyzes information from multiple sources, generating strategic insights and early alerts.',
    'automation.corporate.premium.benefits': 'Benefits Obtained',
    'automation.corporate.premium.benefits.desc': 'Reallocation of talent to more strategic tasks, early detection of threats and opportunities, and sustainable competitive advantage.',
    
    'services.title': 'Our Services',
    'services.what_we_offer': 'What we offer',
    'services.subtitle': 'We develop customized solutions that allow you to maximize the value of your data, from process automation to advanced visualization.',
    'services.automation.title': 'Process Automation',
    'services.automation.subtitle': 'We transform repetitive and manual tasks into intelligent automated workflows to unleash your team\'s potential, reduce errors and maximize operational efficiency.',
    'services.automation.benefits.efficiency': 'Higher Efficiency',
    'services.automation.benefits.accuracy': 'Fewer Errors',
    'services.automation.benefits.time': 'Time Savings',
    'services.automation.problems.title': 'Problems We Solve',
    'services.automation.problems.data_transfer': 'Transferring data between systems',
    'services.automation.problems.reports': 'Creating and formatting periodic reports',
    'services.automation.problems.documents': 'Processing documents (invoices, orders)',
    'services.automation.problems.monitoring': 'Manually monitoring key metrics',
    'services.automation.problems.outdated_info': 'No availability of updated information',
    'services.visualization.title': 'Data Visualization',
    'services.visualization.subtitle': 'We transform complex data into interactive visualizations and dashboards that facilitate understanding and effective decision making.',
    'services.visualization.benefits.clarity': 'Greater Clarity',
    'services.visualization.benefits.insights': 'Quick Insights',
    'services.visualization.benefits.decisions': 'Better Decisions',
    'services.visualization.opportunities.title': 'Opportunities We Provide',
    'services.visualization.opportunities.dashboards': 'Real-time interactive dashboards',
    'services.visualization.opportunities.kpis': 'Visual monitoring of critical KPIs',
    'services.visualization.opportunities.trends': 'Pattern and trend identification',
    'services.visualization.opportunities.alerts': 'Automatic visual alerts',
    'services.visualization.opportunities.storytelling': 'Data storytelling for presentations',
    'services.extraction.title': 'Extraction and Processing',
    'services.extraction.subtitle': 'We extract, transform and unify data from multiple sources to turn it into valuable and actionable information.',
    'services.extraction.benefits.web': 'Data from websites',
    'services.extraction.benefits.db': 'Databases of various types',
    'services.extraction.benefits.integration': 'System integration',
    'services.extraction.opportunities.title': 'Opportunities We Provide',
    'services.extraction.opportunities.web': 'Obtaining information from public and private websites',
    'services.extraction.opportunities.db': 'Extraction and migration of data between SQL, NoSQL databases and APIs',
    'services.extraction.opportunities.integration': 'Data integration with ERPs, CRMs and other platforms',
    'services.extraction.opportunities.pipeline': 'Automation of data pipelines',
    'services.extraction.opportunities.cleaning': 'Unification, cleaning and enrichment of data',
    'services.consulting.title': 'Analytics Consulting',
    'services.training.title': 'Training and Capacity Building',
    'services.unstructured.title': 'Unstructured Data Analysis',
    'services.ai.title': 'AI Integration',
    'services.analytics.title': 'Data Analytics',
    'services.analytics.desc': 'We transform complex data into actionable insights that drive strategic decision-making.',
    'services.automation.desc': 'We optimize repetitive and manual tasks to free up valuable time for your team, reduce errors and improve operational efficiency.',
    'services.visualization.desc': 'We transform complex data into interactive visualizations and dashboards that facilitate understanding and effective decision making.',
    'services.extraction.desc': 'We extract, transform and clean data from multiple sources to convert it into valuable and actionable information for your business.',
    'services.consulting.desc': 'We advise and develop strategies to implement a data-driven culture in your organization, identifying key KPIs and improvement opportunities.',
    'services.training.desc': 'Personalized training programs for your team to develop analytical skills and make the most of available tools.',
    'services.unstructured.desc': 'We extract valuable insights from texts, images and communications through advanced processing and intelligent analysis techniques.',
    'services.ai.desc': 'We implement personalized artificial intelligence solutions that automate complex processes and improve your company\'s predictive capacity.',
    'process.category': 'OUR METHODOLOGY',
    'process.title': 'Work Process',
    'process.subtitle': 'We follow a structured but flexible approach that guarantees optimal results in each project.',
    'process.step1.title': 'Diagnosis',
    'process.step1.desc': 'We analyze your current situation, identify opportunities and define clear objectives.',
    'process.step2.title': 'Design',
    'process.step2.desc': 'We develop a personalized strategy and plan the optimal solution for your needs.',
    'process.step3.title': 'Implementation',
    'process.step3.desc': 'We execute the solution with an agile approach, allowing adjustments during the process.',
    'process.step4.title': 'Optimization',
    'process.step4.desc': 'We monitor results, refine the solution and guarantee knowledge transfer.',
    'process.diagram.title': 'Workflow',
    'process.diagram.subtitle': 'An iterative and adaptive process to maximize the value of your data.',
    'about.title': 'Why choose DataSmart',
    'about.experience': 'Proven Experience',
    'about.experience.desc': 'Years of experience helping companies of all sizes harness the power of their data.',
    'about.innovation': 'Constant Innovation',
    'about.innovation.desc': 'We use the latest technologies and methodologies to deliver cutting-edge solutions.',
    'about.results': 'Measurable Results',
    'about.results.desc': 'We focus on generating real and measurable impact on our clients\' key indicators.',
    'contact.title': 'Start your digital transformation',
    'contact.subtitle': 'Contact us for a free consultation and discover how we can help your company.',
    'contact.cta': 'Contact now',
    'stats.projects': 'Completed Projects',
    'stats.clients': 'Satisfied Clients',
    'stats.efficiency': 'Efficiency Improvement',
    'stats.roi': 'Average ROI',
    'why_us.category': 'WHY CHOOSE US',
    'why_us.title': 'Our Differentiated Approach',
    'why_us.subtitle': 'We combine technical expertise with a deep understanding of business to deliver solutions that generate real and measurable impact.',
    'why_us.scalable.title': 'Scalable Solutions',
    'why_us.scalable.desc': 'Our solutions grow with your business, adapting to your current and future needs without requiring constant reinvestment.',
    'why_us.integral.title': 'Integral Approach',
    'why_us.integral.desc': 'We combine data, technology and business strategy to deliver complete solutions that generate immediate and sustainable value.',
    'why_us.processing.title': 'Intelligent Processing',
    'why_us.processing.desc': 'Specialists in extracting value from multiple formats (text, image, audio, video) using advanced AI technologies.',
    'why_us.development.title': 'Custom Development',
    'why_us.development.desc': 'We create interactive applications with modern technologies like React/Next.js specifically adapted to your needs and workflows.',
    'why_us.support.title': 'Continuous Support',
    'why_us.support.desc': 'We not only implement solutions, but accompany you throughout the process, ensuring adoption and maximizing return on investment.',
    'why_us.results.title': 'Measurable Results',
    'why_us.results.desc': 'We define clear KPIs for each project, guaranteeing tangible results and a quantifiable return on investment from the start.',
    'services.unstructured.opportunities.nlp': 'Natural Language Processing (NLP)',
    'services.unstructured.opportunities.documents': 'Document Analysis',
    'services.unstructured.opportunities.images_video': 'Images and Video',
    'services.unstructured.opportunities.geo': 'Geospatial Data',
    'services.unstructured.opportunities.social': 'Social Media Data',
    'services.unstructured.opportunities.audio': 'Audio Processing',
    'services.unstructured.benefits.text': 'Text Processing',
    'services.unstructured.benefits.image': 'Image Analysis',
    'services.unstructured.benefits.communication': 'Messaging and Communications',
    'services.ai.benefits.automation': 'Intelligent Automation',
    'services.ai.benefits.prediction': 'Advanced Prediction',
    'services.ai.benefits.integration': 'System Integration',
    'services.ai.opportunities.chatbots': 'Personalized Chatbots and Virtual Assistants',
    'services.ai.opportunities.prediction': 'Predictive Analysis and Automatic Recommendations',
    'services.ai.opportunities.security': 'Security Automation and Fraud Detection',
    'services.ai.opportunities.optimization': 'Process Optimization with AI',
    'use_case': 'Use Case',
    'unstructured_data_analysis': 'Unstructured Data Analysis',
    'opportunities_we_provide': 'Opportunities We Provide',
    
    // Specific hardcoded use cases
    'use_case.accounting_api.title': 'Accounting API Integration - Automated Reports',
    'use_case.accounting_api.subtitle': 'Automatic processing of accounting data for real-time dashboards',
    'use_case.quotation_system.title': 'Automated Quotation System',
    'use_case.quotation_system.subtitle': 'Intelligent generation of personalized commercial proposals',
    'use_case.sales_tracking.title': 'Sales Tracking System',
    'use_case.sales_tracking.subtitle': 'Intelligent monitoring of commercial performance and sales pipeline',
    'use_case.communication_classification.title': 'Intelligent Communication Classification',
    'use_case.communication_classification.subtitle': 'Automatic analysis of emails and social media comments',
    'use_case.chatbot_proposals.title': 'Internal Chatbots for Proposal Generation',
    'use_case.chatbot_proposals.subtitle': 'AI assistant to improve commercial team performance',
    'use_case.inventory_management.title': 'Inventory Management System with Alerts',
    'use_case.inventory_management.subtitle': 'Intelligent stock control with demand prediction',
    
    // Common use case sections
    'use_case.challenge': 'The Challenge',
    'use_case.solution': 'Our Solution',
    'use_case.benefits': 'Benefits Obtained',
    
    // Specific content for each use case
    'use_case.accounting_api.challenge.desc': 'Financial information scattered across different accounting systems, manual reports that consume time and are prone to errors.',
    'use_case.accounting_api.solution.desc': 'Direct integration with accounting software API, automatic processing and generation of dashboards with real-time KPIs.',
    'use_case.accounting_api.benefits.desc': 'Complete visibility of profits, portfolio, cash flow, commissions and financial KPIs automatically updated.',
    
    'use_case.quotation_system.challenge.desc': 'Slow manual process for generating quotes, price inconsistencies and excessive customer response time.',
    'use_case.quotation_system.solution.desc': 'Intelligent system that automatically generates personalized quotes based on customer parameters and sales history.',
    'use_case.quotation_system.benefits.desc': '90% reduction in quotation time, price consistency and improvement in customer conversion rate.',
    
    'use_case.sales_tracking.challenge.desc': 'Lack of visibility in sales pipeline, manual prospect tracking and difficulty identifying opportunities.',
    'use_case.sales_tracking.solution.desc': 'Automatic tracking dashboard with alerts, performance metrics and sales closing predictions.',
    'use_case.sales_tracking.benefits.desc': '35% increase in lead conversion, better commercial time management and early opportunity identification.',
    
    'use_case.communication_classification.challenge.desc': 'High volume of emails and comments, slow manual classification and loss of important or urgent messages.',
    'use_case.communication_classification.solution.desc': 'AI that automatically classifies emails and comments by urgency, sentiment and category, with intelligent alerts.',
    'use_case.communication_classification.benefits.desc': '80% reduction in classification time, faster response to urgencies and better customer satisfaction tracking.',
    
    'use_case.chatbot_proposals.challenge.desc': 'Commercial teams with limited access to technical information and difficulty creating consistent and competitive proposals.',
    'use_case.chatbot_proposals.solution.desc': 'Internal chatbot trained with company data that assists the commercial team in creating personalized proposals.',
    'use_case.chatbot_proposals.benefits.desc': '50% improvement in proposal quality, reduction in preparation time and standardization of commercial processes.',
    
    'use_case.inventory_management.challenge.desc': 'Manual inventory control, lack of automatic alerts and difficulty predicting future demand.',
    'use_case.inventory_management.solution.desc': 'Automated system with minimum stock alerts, demand prediction and automatic order optimization.',
    'use_case.inventory_management.benefits.desc': '25% reduction in inventory costs, elimination of stockouts and improvement in purchasing planning.',
    
    // Training and capacity building section
    'training.description': 'Personalized programs for your team to develop analytical skills and make the most of tools like Excel, Power BI, Tableau and AI solutions to enhance data analysis.',
    'training.excel_powerbi_tableau': 'Excel, Power BI and Tableau',
    'training.ai_analysis': 'AI applied to analysis',
    'training.performance_improvement': 'Analytical performance improvement',
    'training.opportunities.excel_training': 'Training in Excel, Power BI and Tableau from basic to advanced level',
    'training.opportunities.ai_tools': 'Use of AI tools to accelerate analysis and decision making',
    'training.opportunities.workshops': 'Practical workshops and real case resolution',
    'training.opportunities.best_practices': 'Implementation of best practices in data processes and analysis',
    'training.opportunities.performance_boost': 'Increase team performance and productivity',
    
    // Use cases intro slide
    'use_cases_intro.category': 'REAL USE CASES',
    'use_cases_intro.title': 'Success Stories',
    'use_cases_intro.subtitle': 'Discover how we have helped companies like yours',
    'use_cases_intro.description': 'These are real examples of how our solutions have transformed our clients\' processes, generating measurable results and improving their operational efficiency.',
    'use_cases_intro.next_slides': 'Below, we present specific cases organized by solution type',
    'use_cases_intro.accounting': 'Accounting Integration',
    'use_cases_intro.quotations': 'Automated Quotations',
    'use_cases_intro.sales_tracking': 'Sales Tracking',
    'use_cases_intro.ai_classification': 'AI Classification',
    'use_cases_intro.chatbots': 'Internal Chatbots',
    'use_cases_intro.inventory': 'Inventory Management',
    'final_leverage.title': 'How Different Companies Leverage Their Data',
    'final_leverage.subtitle': 'Get inspired by real-world examples of transformation and growth powered by data analytics.'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};